// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gbcfqeupruftqqwfbfql.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdiY2ZxZXVwcnVmdHFxd2ZiZnFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MjE5MTYsImV4cCI6MjA2ODk5NzkxNn0.gz1ydWjP2DaXYvhzx-hHulhysWUMq2KSjW0I2WPrHuI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});